sudo: required

branches:
  only:
    - master

language: c
matrix:
  include:
    - dist: trusty
      services:
        - docker
      script:
        - ./build_linux_wheels.sh
    - os: osx
      osx_image: xcode9.4
      script:
        - ./build_mac_os_x_wheels.sh

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./install_osx.sh; fi
