sudo: required

branches:
  only:
    - master

language: c
matrix:
  include:
    - dist: trusty
      services:
        - docker
      script:
        - ./build_linux_wheels.sh
      after_success:
        - ./upload_artifacts_linux.sh
    - os: osx
      osx_image: xcode9.4
      script:
        - ./build_mac_os_x_wheels.sh
      after_success:
        - ./upload_artifacts_mac_os_x.sh

install:
  - ./prepare_setup_py.sh
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then brew tap sqreen/speakeasy && brew install swig@3.0.12; fi
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./install_osx.sh; fi
